enum Color {
  VWORK_WHITE = "#FFFFFF",
  VWORK_RED = "#F50357",
  VWORK_DARK_RED = "#A81347",
  VWORK_BLUE = "#1BC9F5",
  VWORK_DARK_BLUE = "#0A88A8",
  VWORK_LIGHT_BLUE = "#F0F7F8",
  VWORK_YELLOW = "#F5E21B",
  VWORK_GRAY = "#A7A7A7",
  VWORK_BLACK = "#424242",
  VWORK_ORANGE = "#E8AA14",
  VWORK_GREEN = "#6EEB83",
}

export const PROJECT_COLORS = [
  Color.VWORK_BLUE,
  Color.VWORK_RED,
  Color.VWORK_ORANGE,
  Color.VWORK_GREEN,
  Color.VWORK_DARK_BLUE,
  Color.VWORK_DARK_RED,
  Color.VWORK_YELLOW,
];

export default Color;
