version: '3.8'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/frontend/src
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
  backend:
    build: ./backend
    command: bundle exec rails s -p 5000 -b '0.0.0.0'
    ports: 
      - '5000:5000'
    volumes:
      - ./backend:/backend
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
    tty: true
    stdin_open: true
    depends_on: 
      - db
      - redis
      - sidekiq
  db:
    image: mysql:5.7
    ports:
      - "4306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
  sidekiq:
    build: ./backend
    volumes:
      - ./backend:/backend
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: bundle exec sidekiq
    depends_on:
      - redis
      - db
volumes:
  db-data:
  redis:
