source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem 'mysql2', '>= 0.4.4'
gem 'puma', '~> 4.1'
gem 'rails', '~> 6.0.3', '>= 6.0.3.2'
# JSON builder
gem 'jb'
gem 'bcrypt', '~> 3.1.7'
# gem 'image_processing', '~> 1.2'
gem 'redis'
gem 'bootsnap', '>= 1.4.2', :require => false
gem 'sidekiq', '~> 6.1'
gem 'sinatra', :require => false
gem 'redis-namespace'
# CORS設定
gem 'rack-cors'
# 認証系
gem 'devise'
gem 'devise-i18n'
gem 'devise_token_auth'
gem 'rails-i18n'

gem 'slim-rails'
gem 'html2slim'

group :development, :test do
  gem 'byebug', :platforms => %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rspec-rails'
end

group :development do
  gem 'annotate'

  gem 'listen', '~> 3.2'
  gem 'letter_opener'
  gem 'letter_opener_web'

  gem 'rubocop', :require => false
  gem 'rubocop-performance', :require => false
  gem 'rubocop-rails', :require => false

  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'brakeman'
end

group :test do
  gem 'capybara'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', :platforms => %i[mingw mswin x64_mingw jruby]
